//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ShopCartLibrary.Products
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProductEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ProductEntities object using the connection string found in the 'ProductEntities' section of the application configuration file.
        /// </summary>
        public ProductEntities() : base("name=ProductEntities", "ProductEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProductEntities object.
        /// </summary>
        public ProductEntities(string connectionString) : base(connectionString, "ProductEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProductEntities object.
        /// </summary>
        public ProductEntities(EntityConnection connection) : base(connection, "ProductEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductController> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<ProductController>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<ProductController> _Products;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(ProductController product)
        {
            base.AddObject("Products", product);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductController : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="product_Id">Initial value of the Product_Id property.</param>
        /// <param name="product_No">Initial value of the Product_No property.</param>
        /// <param name="category_Code">Initial value of the Category_Code property.</param>
        /// <param name="alias">Initial value of the Alias property.</param>
        public static ProductController CreateProduct(global::System.Int32 product_Id, global::System.Guid product_No, global::System.String category_Code, global::System.String alias)
        {
            ProductController product = new ProductController();
            product.Product_Id = product_Id;
            product.Product_No = product_No;
            product.Category_Code = category_Code;
            product.Alias = alias;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_Id
        {
            get
            {
                return _Product_Id;
            }
            set
            {
                if (_Product_Id != value)
                {
                    OnProduct_IdChanging(value);
                    ReportPropertyChanging("Product_Id");
                    _Product_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Product_Id");
                    OnProduct_IdChanged();
                }
            }
        }
        private global::System.Int32 _Product_Id;
        partial void OnProduct_IdChanging(global::System.Int32 value);
        partial void OnProduct_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Product_No
        {
            get
            {
                return _Product_No;
            }
            set
            {
                OnProduct_NoChanging(value);
                ReportPropertyChanging("Product_No");
                _Product_No = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Product_No");
                OnProduct_NoChanged();
            }
        }
        private global::System.Guid _Product_No;
        partial void OnProduct_NoChanging(global::System.Guid value);
        partial void OnProduct_NoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Code
        {
            get
            {
                return _Product_Code;
            }
            set
            {
                OnProduct_CodeChanging(value);
                ReportPropertyChanging("Product_Code");
                _Product_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Product_Code");
                OnProduct_CodeChanged();
            }
        }
        private global::System.String _Product_Code;
        partial void OnProduct_CodeChanging(global::System.String value);
        partial void OnProduct_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category_Code
        {
            get
            {
                return _Category_Code;
            }
            set
            {
                OnCategory_CodeChanging(value);
                ReportPropertyChanging("Category_Code");
                _Category_Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category_Code");
                OnCategory_CodeChanged();
            }
        }
        private global::System.String _Category_Code;
        partial void OnCategory_CodeChanging(global::System.String value);
        partial void OnCategory_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CultureCode
        {
            get
            {
                return _CultureCode;
            }
            set
            {
                OnCultureCodeChanging(value);
                ReportPropertyChanging("CultureCode");
                _CultureCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CultureCode");
                OnCultureCodeChanged();
            }
        }
        private global::System.String _CultureCode;
        partial void OnCultureCodeChanging(global::System.String value);
        partial void OnCultureCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Manufacturer_Id
        {
            get
            {
                return _Manufacturer_Id;
            }
            set
            {
                OnManufacturer_IdChanging(value);
                ReportPropertyChanging("Manufacturer_Id");
                _Manufacturer_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Manufacturer_Id");
                OnManufacturer_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Manufacturer_Id;
        partial void OnManufacturer_IdChanging(Nullable<global::System.Int32> value);
        partial void OnManufacturer_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Vendor_Id
        {
            get
            {
                return _Vendor_Id;
            }
            set
            {
                OnVendor_IdChanging(value);
                ReportPropertyChanging("Vendor_Id");
                _Vendor_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vendor_Id");
                OnVendor_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Vendor_Id;
        partial void OnVendor_IdChanging(Nullable<global::System.Int32> value);
        partial void OnVendor_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Product_TypeId
        {
            get
            {
                return _Product_TypeId;
            }
            set
            {
                OnProduct_TypeIdChanging(value);
                ReportPropertyChanging("Product_TypeId");
                _Product_TypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Product_TypeId");
                OnProduct_TypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _Product_TypeId;
        partial void OnProduct_TypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnProduct_TypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Name
        {
            get
            {
                return _Product_Name;
            }
            set
            {
                OnProduct_NameChanging(value);
                ReportPropertyChanging("Product_Name");
                _Product_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Product_Name");
                OnProduct_NameChanged();
            }
        }
        private global::System.String _Product_Name;
        partial void OnProduct_NameChanging(global::System.String value);
        partial void OnProduct_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Alias
        {
            get
            {
                return _Alias;
            }
            set
            {
                OnAliasChanging(value);
                ReportPropertyChanging("Alias");
                _Alias = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Alias");
                OnAliasChanged();
            }
        }
        private global::System.String _Alias;
        partial void OnAliasChanging(global::System.String value);
        partial void OnAliasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Discount_Id
        {
            get
            {
                return _Discount_Id;
            }
            set
            {
                OnDiscount_IdChanging(value);
                ReportPropertyChanging("Discount_Id");
                _Discount_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discount_Id");
                OnDiscount_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Discount_Id;
        partial void OnDiscount_IdChanging(Nullable<global::System.Int32> value);
        partial void OnDiscount_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrencyCode
        {
            get
            {
                return _CurrencyCode;
            }
            set
            {
                OnCurrencyCodeChanging(value);
                ReportPropertyChanging("CurrencyCode");
                _CurrencyCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CurrencyCode");
                OnCurrencyCodeChanged();
            }
        }
        private global::System.String _CurrencyCode;
        partial void OnCurrencyCodeChanging(global::System.String value);
        partial void OnCurrencyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NetPrice
        {
            get
            {
                return _NetPrice;
            }
            set
            {
                OnNetPriceChanging(value);
                ReportPropertyChanging("NetPrice");
                _NetPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NetPrice");
                OnNetPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _NetPrice;
        partial void OnNetPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnNetPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GrossPrice
        {
            get
            {
                return _GrossPrice;
            }
            set
            {
                OnGrossPriceChanging(value);
                ReportPropertyChanging("GrossPrice");
                _GrossPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GrossPrice");
                OnGrossPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _GrossPrice;
        partial void OnGrossPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnGrossPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TaxRateId
        {
            get
            {
                return _TaxRateId;
            }
            set
            {
                OnTaxRateIdChanging(value);
                ReportPropertyChanging("TaxRateId");
                _TaxRateId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaxRateId");
                OnTaxRateIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TaxRateId;
        partial void OnTaxRateIdChanging(Nullable<global::System.Int32> value);
        partial void OnTaxRateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> UnitsInStock
        {
            get
            {
                return _UnitsInStock;
            }
            set
            {
                OnUnitsInStockChanging(value);
                ReportPropertyChanging("UnitsInStock");
                _UnitsInStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitsInStock");
                OnUnitsInStockChanged();
            }
        }
        private Nullable<global::System.Int16> _UnitsInStock;
        partial void OnUnitsInStockChanging(Nullable<global::System.Int16> value);
        partial void OnUnitsInStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> UnitsOnOrder
        {
            get
            {
                return _UnitsOnOrder;
            }
            set
            {
                OnUnitsOnOrderChanging(value);
                ReportPropertyChanging("UnitsOnOrder");
                _UnitsOnOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitsOnOrder");
                OnUnitsOnOrderChanged();
            }
        }
        private Nullable<global::System.Int16> _UnitsOnOrder;
        partial void OnUnitsOnOrderChanging(Nullable<global::System.Int16> value);
        partial void OnUnitsOnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> UnitsInAPackage
        {
            get
            {
                return _UnitsInAPackage;
            }
            set
            {
                OnUnitsInAPackageChanging(value);
                ReportPropertyChanging("UnitsInAPackage");
                _UnitsInAPackage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitsInAPackage");
                OnUnitsInAPackageChanged();
            }
        }
        private Nullable<global::System.Int16> _UnitsInAPackage;
        partial void OnUnitsInAPackageChanging(Nullable<global::System.Int16> value);
        partial void OnUnitsInAPackageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> UnitsInBox
        {
            get
            {
                return _UnitsInBox;
            }
            set
            {
                OnUnitsInBoxChanging(value);
                ReportPropertyChanging("UnitsInBox");
                _UnitsInBox = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitsInBox");
                OnUnitsInBoxChanged();
            }
        }
        private Nullable<global::System.Int16> _UnitsInBox;
        partial void OnUnitsInBoxChanging(Nullable<global::System.Int16> value);
        partial void OnUnitsInBoxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Unit
        {
            get
            {
                return _Unit;
            }
            set
            {
                OnUnitChanging(value);
                ReportPropertyChanging("Unit");
                _Unit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Unit");
                OnUnitChanged();
            }
        }
        private global::System.String _Unit;
        partial void OnUnitChanging(global::System.String value);
        partial void OnUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Decimal> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Decimal> value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitOfWeightMeasure
        {
            get
            {
                return _UnitOfWeightMeasure;
            }
            set
            {
                OnUnitOfWeightMeasureChanging(value);
                ReportPropertyChanging("UnitOfWeightMeasure");
                _UnitOfWeightMeasure = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitOfWeightMeasure");
                OnUnitOfWeightMeasureChanged();
            }
        }
        private global::System.String _UnitOfWeightMeasure;
        partial void OnUnitOfWeightMeasureChanging(global::System.String value);
        partial void OnUnitOfWeightMeasureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private Nullable<global::System.Decimal> _Length;
        partial void OnLengthChanging(Nullable<global::System.Decimal> value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Decimal> _Width;
        partial void OnWidthChanging(Nullable<global::System.Decimal> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Decimal> _Height;
        partial void OnHeightChanging(Nullable<global::System.Decimal> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitOfDimensionMeasure
        {
            get
            {
                return _UnitOfDimensionMeasure;
            }
            set
            {
                OnUnitOfDimensionMeasureChanging(value);
                ReportPropertyChanging("UnitOfDimensionMeasure");
                _UnitOfDimensionMeasure = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitOfDimensionMeasure");
                OnUnitOfDimensionMeasureChanged();
            }
        }
        private global::System.String _UnitOfDimensionMeasure;
        partial void OnUnitOfDimensionMeasureChanging(global::System.String value);
        partial void OnUnitOfDimensionMeasureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MinPurchaseQty
        {
            get
            {
                return _MinPurchaseQty;
            }
            set
            {
                OnMinPurchaseQtyChanging(value);
                ReportPropertyChanging("MinPurchaseQty");
                _MinPurchaseQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinPurchaseQty");
                OnMinPurchaseQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _MinPurchaseQty;
        partial void OnMinPurchaseQtyChanging(Nullable<global::System.Int32> value);
        partial void OnMinPurchaseQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxPurchaseQty
        {
            get
            {
                return _MaxPurchaseQty;
            }
            set
            {
                OnMaxPurchaseQtyChanging(value);
                ReportPropertyChanging("MaxPurchaseQty");
                _MaxPurchaseQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxPurchaseQty");
                OnMaxPurchaseQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxPurchaseQty;
        partial void OnMaxPurchaseQtyChanging(Nullable<global::System.Int32> value);
        partial void OnMaxPurchaseQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReorderLevel
        {
            get
            {
                return _ReorderLevel;
            }
            set
            {
                OnReorderLevelChanging(value);
                ReportPropertyChanging("ReorderLevel");
                _ReorderLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReorderLevel");
                OnReorderLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _ReorderLevel;
        partial void OnReorderLevelChanging(Nullable<global::System.Int32> value);
        partial void OnReorderLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Views
        {
            get
            {
                return _Views;
            }
            set
            {
                OnViewsChanging(value);
                ReportPropertyChanging("Views");
                _Views = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Views");
                OnViewsChanged();
            }
        }
        private Nullable<global::System.Int32> _Views;
        partial void OnViewsChanging(Nullable<global::System.Int32> value);
        partial void OnViewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhotoFileName
        {
            get
            {
                return _PhotoFileName;
            }
            set
            {
                OnPhotoFileNameChanging(value);
                ReportPropertyChanging("PhotoFileName");
                _PhotoFileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhotoFileName");
                OnPhotoFileNameChanged();
            }
        }
        private global::System.String _PhotoFileName;
        partial void OnPhotoFileNameChanging(global::System.String value);
        partial void OnPhotoFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThumbnailPhotoFileName
        {
            get
            {
                return _ThumbnailPhotoFileName;
            }
            set
            {
                OnThumbnailPhotoFileNameChanging(value);
                ReportPropertyChanging("ThumbnailPhotoFileName");
                _ThumbnailPhotoFileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThumbnailPhotoFileName");
                OnThumbnailPhotoFileNameChanged();
            }
        }
        private global::System.String _ThumbnailPhotoFileName;
        partial void OnThumbnailPhotoFileNameChanging(global::System.String value);
        partial void OnThumbnailPhotoFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortDescription
        {
            get
            {
                return _ShortDescription;
            }
            set
            {
                OnShortDescriptionChanging(value);
                ReportPropertyChanging("ShortDescription");
                _ShortDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortDescription");
                OnShortDescriptionChanged();
            }
        }
        private global::System.String _ShortDescription;
        partial void OnShortDescriptionChanging(global::System.String value);
        partial void OnShortDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Specification
        {
            get
            {
                return _Specification;
            }
            set
            {
                OnSpecificationChanging(value);
                ReportPropertyChanging("Specification");
                _Specification = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Specification");
                OnSpecificationChanged();
            }
        }
        private global::System.String _Specification;
        partial void OnSpecificationChanging(global::System.String value);
        partial void OnSpecificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Availability
        {
            get
            {
                return _Availability;
            }
            set
            {
                OnAvailabilityChanging(value);
                ReportPropertyChanging("Availability");
                _Availability = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Availability");
                OnAvailabilityChanged();
            }
        }
        private global::System.String _Availability;
        partial void OnAvailabilityChanging(global::System.String value);
        partial void OnAvailabilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PurchaseScope
        {
            get
            {
                return _PurchaseScope;
            }
            set
            {
                OnPurchaseScopeChanging(value);
                ReportPropertyChanging("PurchaseScope");
                _PurchaseScope = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PurchaseScope");
                OnPurchaseScopeChanged();
            }
        }
        private global::System.String _PurchaseScope;
        partial void OnPurchaseScopeChanging(global::System.String value);
        partial void OnPurchaseScopeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Warranty
        {
            get
            {
                return _Warranty;
            }
            set
            {
                OnWarrantyChanging(value);
                ReportPropertyChanging("Warranty");
                _Warranty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Warranty");
                OnWarrantyChanged();
            }
        }
        private global::System.String _Warranty;
        partial void OnWarrantyChanging(global::System.String value);
        partial void OnWarrantyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOnDate
        {
            get
            {
                return _CreatedOnDate;
            }
            set
            {
                OnCreatedOnDateChanging(value);
                ReportPropertyChanging("CreatedOnDate");
                _CreatedOnDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOnDate");
                OnCreatedOnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOnDate;
        partial void OnCreatedOnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedOnDate
        {
            get
            {
                return _LastModifiedOnDate;
            }
            set
            {
                OnLastModifiedOnDateChanging(value);
                ReportPropertyChanging("LastModifiedOnDate");
                _LastModifiedOnDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedOnDate");
                OnLastModifiedOnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedOnDate;
        partial void OnLastModifiedOnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedOnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OnlineTransactionFlag
        {
            get
            {
                return _OnlineTransactionFlag;
            }
            set
            {
                OnOnlineTransactionFlagChanging(value);
                ReportPropertyChanging("OnlineTransactionFlag");
                _OnlineTransactionFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OnlineTransactionFlag");
                OnOnlineTransactionFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _OnlineTransactionFlag;
        partial void OnOnlineTransactionFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnOnlineTransactionFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> InfoStatus
        {
            get
            {
                return _InfoStatus;
            }
            set
            {
                OnInfoStatusChanging(value);
                ReportPropertyChanging("InfoStatus");
                _InfoStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InfoStatus");
                OnInfoStatusChanged();
            }
        }
        private Nullable<global::System.Byte> _InfoStatus;
        partial void OnInfoStatusChanging(Nullable<global::System.Byte> value);
        partial void OnInfoStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> PriceStatus
        {
            get
            {
                return _PriceStatus;
            }
            set
            {
                OnPriceStatusChanging(value);
                ReportPropertyChanging("PriceStatus");
                _PriceStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PriceStatus");
                OnPriceStatusChanged();
            }
        }
        private Nullable<global::System.Byte> _PriceStatus;
        partial void OnPriceStatusChanging(Nullable<global::System.Byte> value);
        partial void OnPriceStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> QtyStatus
        {
            get
            {
                return _QtyStatus;
            }
            set
            {
                OnQtyStatusChanging(value);
                ReportPropertyChanging("QtyStatus");
                _QtyStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtyStatus");
                OnQtyStatusChanged();
            }
        }
        private Nullable<global::System.Byte> _QtyStatus;
        partial void OnQtyStatusChanging(Nullable<global::System.Byte> value);
        partial void OnQtyStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Discontinued
        {
            get
            {
                return _Discontinued;
            }
            set
            {
                OnDiscontinuedChanging(value);
                ReportPropertyChanging("Discontinued");
                _Discontinued = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discontinued");
                OnDiscontinuedChanged();
            }
        }
        private Nullable<global::System.Byte> _Discontinued;
        partial void OnDiscontinuedChanging(Nullable<global::System.Byte> value);
        partial void OnDiscontinuedChanged();

        #endregion
    
    }

    #endregion
    
}
