//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ArticleLibrary
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ArticleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ArticleEntities object using the connection string found in the 'ArticleEntities' section of the application configuration file.
        /// </summary>
        public ArticleEntities() : base("name=ArticleEntities", "ArticleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ArticleEntities object.
        /// </summary>
        public ArticleEntities(string connectionString) : base(connectionString, "ArticleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ArticleEntities object.
        /// </summary>
        public ArticleEntities(EntityConnection connection) : base(connection, "ArticleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ArticleCategory> ArticleCategories
        {
            get
            {
                if ((_ArticleCategories == null))
                {
                    _ArticleCategories = base.CreateObjectSet<ArticleCategory>("ArticleCategories");
                }
                return _ArticleCategories;
            }
        }
        private ObjectSet<ArticleCategory> _ArticleCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article> Articles
        {
            get
            {
                if ((_Articles == null))
                {
                    _Articles = base.CreateObjectSet<Article>("Articles");
                }
                return _Articles;
            }
        }
        private ObjectSet<Article> _Articles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AddressType> AddressTypes
        {
            get
            {
                if ((_AddressTypes == null))
                {
                    _AddressTypes = base.CreateObjectSet<AddressType>("AddressTypes");
                }
                return _AddressTypes;
            }
        }
        private ObjectSet<AddressType> _AddressTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ArticleComment> ArticleComments
        {
            get
            {
                if ((_ArticleComments == null))
                {
                    _ArticleComments = base.CreateObjectSet<ArticleComment>("ArticleComments");
                }
                return _ArticleComments;
            }
        }
        private ObjectSet<ArticleComment> _ArticleComments;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ArticleCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticleCategories(ArticleCategory articleCategory)
        {
            base.AddObject("ArticleCategories", articleCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Articles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticles(Article article)
        {
            base.AddObject("Articles", article);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AddressTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddressTypes(AddressType addressType)
        {
            base.AddObject("AddressTypes", addressType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ArticleComments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticleComments(ArticleComment articleComment)
        {
            base.AddObject("ArticleComments", articleComment);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="categoryCode">No Metadata Documentation available.</param>
        public ObjectResult<ArticleCategory> ArticleCategories_GetAllParentNodesOfSelectedNode(global::System.String categoryCode)
        {
            ObjectParameter categoryCodeParameter;
            if (categoryCode != null)
            {
                categoryCodeParameter = new ObjectParameter("CategoryCode", categoryCode);
            }
            else
            {
                categoryCodeParameter = new ObjectParameter("CategoryCode", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<ArticleCategory>("ArticleCategories_GetAllParentNodesOfSelectedNode", categoryCodeParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="categoryCode">No Metadata Documentation available.</param>
        public ObjectResult<ArticleCategory> ArticleCategories_GetAllParentNodesOfSelectedNode(global::System.String categoryCode, MergeOption mergeOption)
        {
            ObjectParameter categoryCodeParameter;
            if (categoryCode != null)
            {
                categoryCodeParameter = new ObjectParameter("CategoryCode", categoryCode);
            }
            else
            {
                categoryCodeParameter = new ObjectParameter("CategoryCode", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<ArticleCategory>("ArticleCategories_GetAllParentNodesOfSelectedNode", mergeOption, categoryCodeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="categoryCode">No Metadata Documentation available.</param>
        public ObjectResult<ArticleCategory> ArticleCategories_GetAllChildrenNodesOfSelectedNode(global::System.String categoryCode)
        {
            ObjectParameter categoryCodeParameter;
            if (categoryCode != null)
            {
                categoryCodeParameter = new ObjectParameter("CategoryCode", categoryCode);
            }
            else
            {
                categoryCodeParameter = new ObjectParameter("CategoryCode", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<ArticleCategory>("ArticleCategories_GetAllChildrenNodesOfSelectedNode", categoryCodeParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="categoryCode">No Metadata Documentation available.</param>
        public ObjectResult<ArticleCategory> ArticleCategories_GetAllChildrenNodesOfSelectedNode(global::System.String categoryCode, MergeOption mergeOption)
        {
            ObjectParameter categoryCodeParameter;
            if (categoryCode != null)
            {
                categoryCodeParameter = new ObjectParameter("CategoryCode", categoryCode);
            }
            else
            {
                categoryCodeParameter = new ObjectParameter("CategoryCode", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<ArticleCategory>("ArticleCategories_GetAllChildrenNodesOfSelectedNode", mergeOption, categoryCodeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<ArticleComment> sp_ArticleComments_GetList()
        {
            return base.ExecuteFunction<ArticleComment>("sp_ArticleComments_GetList");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<ArticleComment> sp_ArticleComments_GetList(MergeOption mergeOption)
        {
            return base.ExecuteFunction<ArticleComment>("sp_ArticleComments_GetList", mergeOption);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ArticleModel", Name="AddressType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AddressType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AddressType object.
        /// </summary>
        /// <param name="addressTypeId">Initial value of the AddressTypeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static AddressType CreateAddressType(global::System.Int32 addressTypeId, global::System.String name)
        {
            AddressType addressType = new AddressType();
            addressType.AddressTypeId = addressTypeId;
            addressType.Name = name;
            return addressType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressTypeId
        {
            get
            {
                return _AddressTypeId;
            }
            set
            {
                if (_AddressTypeId != value)
                {
                    OnAddressTypeIdChanging(value);
                    ReportPropertyChanging("AddressTypeId");
                    _AddressTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AddressTypeId");
                    OnAddressTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _AddressTypeId;
        partial void OnAddressTypeIdChanging(global::System.Int32 value);
        partial void OnAddressTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ArticleModel", Name="Article")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article object.
        /// </summary>
        /// <param name="articleId">Initial value of the ArticleId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="headline">Initial value of the Headline property.</param>
        /// <param name="mainText">Initial value of the MainText property.</param>
        /// <param name="sortKey">Initial value of the SortKey property.</param>
        public static Article CreateArticle(global::System.Int32 articleId, global::System.String title, global::System.String headline, global::System.String mainText, global::System.Int32 sortKey)
        {
            Article article = new Article();
            article.ArticleId = articleId;
            article.Title = title;
            article.Headline = headline;
            article.MainText = mainText;
            article.SortKey = sortKey;
            return article;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PortalId
        {
            get
            {
                return _PortalId;
            }
            set
            {
                OnPortalIdChanging(value);
                ReportPropertyChanging("PortalId");
                _PortalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortalId");
                OnPortalIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PortalId;
        partial void OnPortalIdChanging(Nullable<global::System.Int32> value);
        partial void OnPortalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CultureCode
        {
            get
            {
                return _CultureCode;
            }
            set
            {
                OnCultureCodeChanging(value);
                ReportPropertyChanging("CultureCode");
                _CultureCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CultureCode");
                OnCultureCodeChanged();
            }
        }
        private global::System.String _CultureCode;
        partial void OnCultureCodeChanging(global::System.String value);
        partial void OnCultureCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArticleId
        {
            get
            {
                return _ArticleId;
            }
            set
            {
                if (_ArticleId != value)
                {
                    OnArticleIdChanging(value);
                    ReportPropertyChanging("ArticleId");
                    _ArticleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ArticleId");
                    OnArticleIdChanged();
                }
            }
        }
        private global::System.Int32 _ArticleId;
        partial void OnArticleIdChanging(global::System.Int32 value);
        partial void OnArticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoryCode
        {
            get
            {
                return _CategoryCode;
            }
            set
            {
                OnCategoryCodeChanging(value);
                ReportPropertyChanging("CategoryCode");
                _CategoryCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CategoryCode");
                OnCategoryCodeChanged();
            }
        }
        private global::System.String _CategoryCode;
        partial void OnCategoryCodeChanging(global::System.String value);
        partial void OnCategoryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Headline
        {
            get
            {
                return _Headline;
            }
            set
            {
                OnHeadlineChanging(value);
                ReportPropertyChanging("Headline");
                _Headline = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Headline");
                OnHeadlineChanged();
            }
        }
        private global::System.String _Headline;
        partial void OnHeadlineChanging(global::System.String value);
        partial void OnHeadlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alias
        {
            get
            {
                return _Alias;
            }
            set
            {
                OnAliasChanging(value);
                ReportPropertyChanging("Alias");
                _Alias = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alias");
                OnAliasChanged();
            }
        }
        private global::System.String _Alias;
        partial void OnAliasChanging(global::System.String value);
        partial void OnAliasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Abstract
        {
            get
            {
                return _Abstract;
            }
            set
            {
                OnAbstractChanging(value);
                ReportPropertyChanging("Abstract");
                _Abstract = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Abstract");
                OnAbstractChanged();
            }
        }
        private global::System.String _Abstract;
        partial void OnAbstractChanging(global::System.String value);
        partial void OnAbstractChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FrontImage
        {
            get
            {
                return _FrontImage;
            }
            set
            {
                OnFrontImageChanging(value);
                ReportPropertyChanging("FrontImage");
                _FrontImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FrontImage");
                OnFrontImageChanged();
            }
        }
        private global::System.String _FrontImage;
        partial void OnFrontImageChanging(global::System.String value);
        partial void OnFrontImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MainImage
        {
            get
            {
                return _MainImage;
            }
            set
            {
                OnMainImageChanging(value);
                ReportPropertyChanging("MainImage");
                _MainImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MainImage");
                OnMainImageChanged();
            }
        }
        private global::System.String _MainImage;
        partial void OnMainImageChanging(global::System.String value);
        partial void OnMainImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MainText
        {
            get
            {
                return _MainText;
            }
            set
            {
                OnMainTextChanging(value);
                ReportPropertyChanging("MainText");
                _MainText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MainText");
                OnMainTextChanged();
            }
        }
        private global::System.String _MainText;
        partial void OnMainTextChanging(global::System.String value);
        partial void OnMainTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavigateUrl
        {
            get
            {
                return _NavigateUrl;
            }
            set
            {
                OnNavigateUrlChanging(value);
                ReportPropertyChanging("NavigateUrl");
                _NavigateUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavigateUrl");
                OnNavigateUrlChanged();
            }
        }
        private global::System.String _NavigateUrl;
        partial void OnNavigateUrlChanging(global::System.String value);
        partial void OnNavigateUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Authors
        {
            get
            {
                return _Authors;
            }
            set
            {
                OnAuthorsChanging(value);
                ReportPropertyChanging("Authors");
                _Authors = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Authors");
                OnAuthorsChanged();
            }
        }
        private global::System.String _Authors;
        partial void OnAuthorsChanging(global::System.String value);
        partial void OnAuthorsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SortKey
        {
            get
            {
                return _SortKey;
            }
            set
            {
                OnSortKeyChanging(value);
                ReportPropertyChanging("SortKey");
                _SortKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortKey");
                OnSortKeyChanged();
            }
        }
        private global::System.Int32 _SortKey;
        partial void OnSortKeyChanging(global::System.Int32 value);
        partial void OnSortKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalRates
        {
            get
            {
                return _TotalRates;
            }
            set
            {
                OnTotalRatesChanging(value);
                ReportPropertyChanging("TotalRates");
                _TotalRates = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalRates");
                OnTotalRatesChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalRates;
        partial void OnTotalRatesChanging(Nullable<global::System.Int32> value);
        partial void OnTotalRatesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalViews
        {
            get
            {
                return _TotalViews;
            }
            set
            {
                OnTotalViewsChanging(value);
                ReportPropertyChanging("TotalViews");
                _TotalViews = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalViews");
                OnTotalViewsChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalViews;
        partial void OnTotalViewsChanging(Nullable<global::System.Int32> value);
        partial void OnTotalViewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateAmended
        {
            get
            {
                return _DateAmended;
            }
            set
            {
                OnDateAmendedChanging(value);
                ReportPropertyChanging("DateAmended");
                _DateAmended = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAmended");
                OnDateAmendedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateAmended;
        partial void OnDateAmendedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateAmendedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> PostedBy
        {
            get
            {
                return _PostedBy;
            }
            set
            {
                OnPostedByChanging(value);
                ReportPropertyChanging("PostedBy");
                _PostedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostedBy");
                OnPostedByChanged();
            }
        }
        private Nullable<global::System.Guid> _PostedBy;
        partial void OnPostedByChanging(Nullable<global::System.Guid> value);
        partial void OnPostedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private Nullable<global::System.Guid> _UpdatedBy;
        partial void OnUpdatedByChanging(Nullable<global::System.Guid> value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPLog
        {
            get
            {
                return _IPLog;
            }
            set
            {
                OnIPLogChanging(value);
                ReportPropertyChanging("IPLog");
                _IPLog = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPLog");
                OnIPLogChanged();
            }
        }
        private global::System.String _IPLog;
        partial void OnIPLogChanging(global::System.String value);
        partial void OnIPLogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPLastUpdated
        {
            get
            {
                return _IPLastUpdated;
            }
            set
            {
                OnIPLastUpdatedChanging(value);
                ReportPropertyChanging("IPLastUpdated");
                _IPLastUpdated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPLastUpdated");
                OnIPLastUpdatedChanged();
            }
        }
        private global::System.String _IPLastUpdated;
        partial void OnIPLastUpdatedChanging(global::System.String value);
        partial void OnIPLastUpdatedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ArticleModel", Name="ArticleCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ArticleCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ArticleCategory object.
        /// </summary>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="categoryCode">Initial value of the CategoryCode property.</param>
        public static ArticleCategory CreateArticleCategory(global::System.Int32 categoryId, global::System.String categoryCode)
        {
            ArticleCategory articleCategory = new ArticleCategory();
            articleCategory.CategoryId = categoryId;
            articleCategory.CategoryCode = categoryCode;
            return articleCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PortalId
        {
            get
            {
                return _PortalId;
            }
            set
            {
                OnPortalIdChanging(value);
                ReportPropertyChanging("PortalId");
                _PortalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortalId");
                OnPortalIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PortalId;
        partial void OnPortalIdChanging(Nullable<global::System.Int32> value);
        partial void OnPortalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CultureCode
        {
            get
            {
                return _CultureCode;
            }
            set
            {
                OnCultureCodeChanging(value);
                ReportPropertyChanging("CultureCode");
                _CultureCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CultureCode");
                OnCultureCodeChanged();
            }
        }
        private global::System.String _CultureCode;
        partial void OnCultureCodeChanging(global::System.String value);
        partial void OnCultureCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                if (_CategoryId != value)
                {
                    OnCategoryIdChanging(value);
                    ReportPropertyChanging("CategoryId");
                    _CategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryId");
                    OnCategoryIdChanged();
                }
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryCode
        {
            get
            {
                return _CategoryCode;
            }
            set
            {
                OnCategoryCodeChanging(value);
                ReportPropertyChanging("CategoryCode");
                _CategoryCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryCode");
                OnCategoryCodeChanged();
            }
        }
        private global::System.String _CategoryCode;
        partial void OnCategoryCodeChanging(global::System.String value);
        partial void OnCategoryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alias
        {
            get
            {
                return _Alias;
            }
            set
            {
                OnAliasChanging(value);
                ReportPropertyChanging("Alias");
                _Alias = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alias");
                OnAliasChanged();
            }
        }
        private global::System.String _Alias;
        partial void OnAliasChanging(global::System.String value);
        partial void OnAliasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Depth
        {
            get
            {
                return _Depth;
            }
            set
            {
                OnDepthChanging(value);
                ReportPropertyChanging("Depth");
                _Depth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Depth");
                OnDepthChanged();
            }
        }
        private Nullable<global::System.Int32> _Depth;
        partial void OnDepthChanging(Nullable<global::System.Int32> value);
        partial void OnDepthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lineage
        {
            get
            {
                return _Lineage;
            }
            set
            {
                OnLineageChanging(value);
                ReportPropertyChanging("Lineage");
                _Lineage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lineage");
                OnLineageChanged();
            }
        }
        private global::System.String _Lineage;
        partial void OnLineageChanging(global::System.String value);
        partial void OnLineageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortKey
        {
            get
            {
                return _SortKey;
            }
            set
            {
                OnSortKeyChanging(value);
                ReportPropertyChanging("SortKey");
                _SortKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortKey");
                OnSortKeyChanged();
            }
        }
        private Nullable<global::System.Int32> _SortKey;
        partial void OnSortKeyChanging(Nullable<global::System.Int32> value);
        partial void OnSortKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoryImage
        {
            get
            {
                return _CategoryImage;
            }
            set
            {
                OnCategoryImageChanging(value);
                ReportPropertyChanging("CategoryImage");
                _CategoryImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CategoryImage");
                OnCategoryImageChanged();
            }
        }
        private global::System.String _CategoryImage;
        partial void OnCategoryImageChanging(global::System.String value);
        partial void OnCategoryImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavigateUrl
        {
            get
            {
                return _NavigateUrl;
            }
            set
            {
                OnNavigateUrlChanging(value);
                ReportPropertyChanging("NavigateUrl");
                _NavigateUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavigateUrl");
                OnNavigateUrlChanged();
            }
        }
        private global::System.String _NavigateUrl;
        partial void OnNavigateUrlChanging(global::System.String value);
        partial void OnNavigateUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateAmended
        {
            get
            {
                return _DateAmended;
            }
            set
            {
                OnDateAmendedChanging(value);
                ReportPropertyChanging("DateAmended");
                _DateAmended = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAmended");
                OnDateAmendedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateAmended;
        partial void OnDateAmendedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateAmendedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserLog
        {
            get
            {
                return _UserLog;
            }
            set
            {
                OnUserLogChanging(value);
                ReportPropertyChanging("UserLog");
                _UserLog = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserLog");
                OnUserLogChanged();
            }
        }
        private global::System.String _UserLog;
        partial void OnUserLogChanging(global::System.String value);
        partial void OnUserLogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserLastUpdated
        {
            get
            {
                return _UserLastUpdated;
            }
            set
            {
                OnUserLastUpdatedChanging(value);
                ReportPropertyChanging("UserLastUpdated");
                _UserLastUpdated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserLastUpdated");
                OnUserLastUpdatedChanged();
            }
        }
        private global::System.String _UserLastUpdated;
        partial void OnUserLastUpdatedChanging(global::System.String value);
        partial void OnUserLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPLog
        {
            get
            {
                return _IPLog;
            }
            set
            {
                OnIPLogChanging(value);
                ReportPropertyChanging("IPLog");
                _IPLog = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPLog");
                OnIPLogChanged();
            }
        }
        private global::System.String _IPLog;
        partial void OnIPLogChanging(global::System.String value);
        partial void OnIPLogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPLastUpdated
        {
            get
            {
                return _IPLastUpdated;
            }
            set
            {
                OnIPLastUpdatedChanging(value);
                ReportPropertyChanging("IPLastUpdated");
                _IPLastUpdated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPLastUpdated");
                OnIPLastUpdatedChanged();
            }
        }
        private global::System.String _IPLastUpdated;
        partial void OnIPLastUpdatedChanging(global::System.String value);
        partial void OnIPLastUpdatedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ArticleModel", Name="ArticleComment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ArticleComment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ArticleComment object.
        /// </summary>
        /// <param name="articleId">Initial value of the ArticleId property.</param>
        /// <param name="commentId">Initial value of the CommentId property.</param>
        /// <param name="commentName">Initial value of the CommentName property.</param>
        /// <param name="commentEmail">Initial value of the CommentEmail property.</param>
        /// <param name="commentText">Initial value of the CommentText property.</param>
        public static ArticleComment CreateArticleComment(global::System.Int32 articleId, global::System.Int32 commentId, global::System.String commentName, global::System.String commentEmail, global::System.String commentText)
        {
            ArticleComment articleComment = new ArticleComment();
            articleComment.ArticleId = articleId;
            articleComment.CommentId = commentId;
            articleComment.CommentName = commentName;
            articleComment.CommentEmail = commentEmail;
            articleComment.CommentText = commentText;
            return articleComment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArticleId
        {
            get
            {
                return _ArticleId;
            }
            set
            {
                OnArticleIdChanging(value);
                ReportPropertyChanging("ArticleId");
                _ArticleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArticleId");
                OnArticleIdChanged();
            }
        }
        private global::System.Int32 _ArticleId;
        partial void OnArticleIdChanging(global::System.Int32 value);
        partial void OnArticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommentId
        {
            get
            {
                return _CommentId;
            }
            set
            {
                if (_CommentId != value)
                {
                    OnCommentIdChanging(value);
                    ReportPropertyChanging("CommentId");
                    _CommentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CommentId");
                    OnCommentIdChanged();
                }
            }
        }
        private global::System.Int32 _CommentId;
        partial void OnCommentIdChanging(global::System.Int32 value);
        partial void OnCommentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CommentName
        {
            get
            {
                return _CommentName;
            }
            set
            {
                OnCommentNameChanging(value);
                ReportPropertyChanging("CommentName");
                _CommentName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CommentName");
                OnCommentNameChanged();
            }
        }
        private global::System.String _CommentName;
        partial void OnCommentNameChanging(global::System.String value);
        partial void OnCommentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CommentEmail
        {
            get
            {
                return _CommentEmail;
            }
            set
            {
                OnCommentEmailChanging(value);
                ReportPropertyChanging("CommentEmail");
                _CommentEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CommentEmail");
                OnCommentEmailChanged();
            }
        }
        private global::System.String _CommentEmail;
        partial void OnCommentEmailChanging(global::System.String value);
        partial void OnCommentEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CommentText
        {
            get
            {
                return _CommentText;
            }
            set
            {
                OnCommentTextChanging(value);
                ReportPropertyChanging("CommentText");
                _CommentText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CommentText");
                OnCommentTextChanged();
            }
        }
        private global::System.String _CommentText;
        partial void OnCommentTextChanging(global::System.String value);
        partial void OnCommentTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsReply
        {
            get
            {
                return _IsReply;
            }
            set
            {
                OnIsReplyChanging(value);
                ReportPropertyChanging("IsReply");
                _IsReply = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReply");
                OnIsReplyChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsReply;
        partial void OnIsReplyChanging(Nullable<global::System.Boolean> value);
        partial void OnIsReplyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Publish
        {
            get
            {
                return _Publish;
            }
            set
            {
                OnPublishChanging(value);
                ReportPropertyChanging("Publish");
                _Publish = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Publish");
                OnPublishChanged();
            }
        }
        private global::System.String _Publish;
        partial void OnPublishChanging(global::System.String value);
        partial void OnPublishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DatePosted
        {
            get
            {
                return _DatePosted;
            }
            set
            {
                OnDatePostedChanging(value);
                ReportPropertyChanging("DatePosted");
                _DatePosted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatePosted");
                OnDatePostedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DatePosted;
        partial void OnDatePostedChanging(Nullable<global::System.DateTime> value);
        partial void OnDatePostedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUpdated;
        partial void OnDateUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserLog
        {
            get
            {
                return _UserLog;
            }
            set
            {
                OnUserLogChanging(value);
                ReportPropertyChanging("UserLog");
                _UserLog = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserLog");
                OnUserLogChanged();
            }
        }
        private Nullable<global::System.Guid> _UserLog;
        partial void OnUserLogChanging(Nullable<global::System.Guid> value);
        partial void OnUserLogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserLastUpdated
        {
            get
            {
                return _UserLastUpdated;
            }
            set
            {
                OnUserLastUpdatedChanging(value);
                ReportPropertyChanging("UserLastUpdated");
                _UserLastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserLastUpdated");
                OnUserLastUpdatedChanged();
            }
        }
        private Nullable<global::System.Guid> _UserLastUpdated;
        partial void OnUserLastUpdatedChanging(Nullable<global::System.Guid> value);
        partial void OnUserLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPLog
        {
            get
            {
                return _IPLog;
            }
            set
            {
                OnIPLogChanging(value);
                ReportPropertyChanging("IPLog");
                _IPLog = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPLog");
                OnIPLogChanged();
            }
        }
        private global::System.String _IPLog;
        partial void OnIPLogChanging(global::System.String value);
        partial void OnIPLogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPLastUpdated
        {
            get
            {
                return _IPLastUpdated;
            }
            set
            {
                OnIPLastUpdatedChanging(value);
                ReportPropertyChanging("IPLastUpdated");
                _IPLastUpdated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPLastUpdated");
                OnIPLastUpdatedChanged();
            }
        }
        private global::System.String _IPLastUpdated;
        partial void OnIPLastUpdatedChanging(global::System.String value);
        partial void OnIPLastUpdatedChanged();

        #endregion
    
    }

    #endregion
    
}
