//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CommonLibrary.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CommonEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CommonEntities object using the connection string found in the 'CommonEntities' section of the application configuration file.
        /// </summary>
        public CommonEntities() : base("name=CommonEntities", "CommonEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CommonEntities object.
        /// </summary>
        public CommonEntities(string connectionString) : base(connectionString, "CommonEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CommonEntities object.
        /// </summary>
        public CommonEntities(EntityConnection connection) : base(connection, "CommonEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aspnet_ContentItems> aspnet_ContentItems
        {
            get
            {
                if ((_aspnet_ContentItems == null))
                {
                    _aspnet_ContentItems = base.CreateObjectSet<aspnet_ContentItems>("aspnet_ContentItems");
                }
                return _aspnet_ContentItems;
            }
        }
        private ObjectSet<aspnet_ContentItems> _aspnet_ContentItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aspnet_Routes> aspnet_Routes
        {
            get
            {
                if ((_aspnet_Routes == null))
                {
                    _aspnet_Routes = base.CreateObjectSet<aspnet_Routes>("aspnet_Routes");
                }
                return _aspnet_Routes;
            }
        }
        private ObjectSet<aspnet_Routes> _aspnet_Routes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aspnet_ContentItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaspnet_ContentItems(aspnet_ContentItems aspnet_ContentItems)
        {
            base.AddObject("aspnet_ContentItems", aspnet_ContentItems);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aspnet_Routes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaspnet_Routes(aspnet_Routes aspnet_Routes)
        {
            base.AddObject("aspnet_Routes", aspnet_Routes);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="aspnet_ContentItems")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aspnet_ContentItems : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aspnet_ContentItems object.
        /// </summary>
        /// <param name="contentItemId">Initial value of the ContentItemId property.</param>
        /// <param name="contentTypeId">Initial value of the ContentTypeId property.</param>
        /// <param name="indexed">Initial value of the Indexed property.</param>
        public static aspnet_ContentItems Createaspnet_ContentItems(global::System.Int32 contentItemId, global::System.Int32 contentTypeId, global::System.Boolean indexed)
        {
            aspnet_ContentItems aspnet_ContentItems = new aspnet_ContentItems();
            aspnet_ContentItems.ContentItemId = contentItemId;
            aspnet_ContentItems.ContentTypeId = contentTypeId;
            aspnet_ContentItems.Indexed = indexed;
            return aspnet_ContentItems;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentItemId
        {
            get
            {
                return _ContentItemId;
            }
            set
            {
                if (_ContentItemId != value)
                {
                    OnContentItemIdChanging(value);
                    ReportPropertyChanging("ContentItemId");
                    _ContentItemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ContentItemId");
                    OnContentItemIdChanged();
                }
            }
        }
        private global::System.Int32 _ContentItemId;
        partial void OnContentItemIdChanging(global::System.Int32 value);
        partial void OnContentItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentTypeId
        {
            get
            {
                return _ContentTypeId;
            }
            set
            {
                OnContentTypeIdChanging(value);
                ReportPropertyChanging("ContentTypeId");
                _ContentTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentTypeId");
                OnContentTypeIdChanged();
            }
        }
        private global::System.Int32 _ContentTypeId;
        partial void OnContentTypeIdChanging(global::System.Int32 value);
        partial void OnContentTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContentKey
        {
            get
            {
                return _ContentKey;
            }
            set
            {
                OnContentKeyChanging(value);
                ReportPropertyChanging("ContentKey");
                _ContentKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContentKey");
                OnContentKeyChanged();
            }
        }
        private global::System.String _ContentKey;
        partial void OnContentKeyChanging(global::System.String value);
        partial void OnContentKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Indexed
        {
            get
            {
                return _Indexed;
            }
            set
            {
                OnIndexedChanging(value);
                ReportPropertyChanging("Indexed");
                _Indexed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Indexed");
                OnIndexedChanged();
            }
        }
        private global::System.Boolean _Indexed;
        partial void OnIndexedChanging(global::System.Boolean value);
        partial void OnIndexedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="aspnet_Routes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aspnet_Routes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aspnet_Routes object.
        /// </summary>
        /// <param name="portalId">Initial value of the PortalId property.</param>
        /// <param name="contentItemId">Initial value of the ContentItemId property.</param>
        /// <param name="cultureCode">Initial value of the CultureCode property.</param>
        /// <param name="routeId">Initial value of the RouteId property.</param>
        /// <param name="routeName">Initial value of the RouteName property.</param>
        /// <param name="routeUrl">Initial value of the RouteUrl property.</param>
        /// <param name="physicalFile">Initial value of the PhysicalFile property.</param>
        /// <param name="checkPhysicalUrlAccess">Initial value of the CheckPhysicalUrlAccess property.</param>
        /// <param name="routeValueDictionary">Initial value of the RouteValueDictionary property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="listOrder">Initial value of the ListOrder property.</param>
        /// <param name="discontinued">Initial value of the Discontinued property.</param>
        public static aspnet_Routes Createaspnet_Routes(global::System.Int32 portalId, global::System.Int32 contentItemId, global::System.String cultureCode, global::System.Int32 routeId, global::System.String routeName, global::System.String routeUrl, global::System.String physicalFile, global::System.Boolean checkPhysicalUrlAccess, global::System.String routeValueDictionary, global::System.String description, global::System.Int32 listOrder, global::System.Boolean discontinued)
        {
            aspnet_Routes aspnet_Routes = new aspnet_Routes();
            aspnet_Routes.PortalId = portalId;
            aspnet_Routes.ContentItemId = contentItemId;
            aspnet_Routes.CultureCode = cultureCode;
            aspnet_Routes.RouteId = routeId;
            aspnet_Routes.RouteName = routeName;
            aspnet_Routes.RouteUrl = routeUrl;
            aspnet_Routes.PhysicalFile = physicalFile;
            aspnet_Routes.CheckPhysicalUrlAccess = checkPhysicalUrlAccess;
            aspnet_Routes.RouteValueDictionary = routeValueDictionary;
            aspnet_Routes.Description = description;
            aspnet_Routes.ListOrder = listOrder;
            aspnet_Routes.Discontinued = discontinued;
            return aspnet_Routes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PortalId
        {
            get
            {
                return _PortalId;
            }
            set
            {
                OnPortalIdChanging(value);
                ReportPropertyChanging("PortalId");
                _PortalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortalId");
                OnPortalIdChanged();
            }
        }
        private global::System.Int32 _PortalId;
        partial void OnPortalIdChanging(global::System.Int32 value);
        partial void OnPortalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentItemId
        {
            get
            {
                return _ContentItemId;
            }
            set
            {
                OnContentItemIdChanging(value);
                ReportPropertyChanging("ContentItemId");
                _ContentItemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentItemId");
                OnContentItemIdChanged();
            }
        }
        private global::System.Int32 _ContentItemId;
        partial void OnContentItemIdChanging(global::System.Int32 value);
        partial void OnContentItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CultureCode
        {
            get
            {
                return _CultureCode;
            }
            set
            {
                OnCultureCodeChanging(value);
                ReportPropertyChanging("CultureCode");
                _CultureCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CultureCode");
                OnCultureCodeChanged();
            }
        }
        private global::System.String _CultureCode;
        partial void OnCultureCodeChanging(global::System.String value);
        partial void OnCultureCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RouteId
        {
            get
            {
                return _RouteId;
            }
            set
            {
                if (_RouteId != value)
                {
                    OnRouteIdChanging(value);
                    ReportPropertyChanging("RouteId");
                    _RouteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RouteId");
                    OnRouteIdChanged();
                }
            }
        }
        private global::System.Int32 _RouteId;
        partial void OnRouteIdChanging(global::System.Int32 value);
        partial void OnRouteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RouteName
        {
            get
            {
                return _RouteName;
            }
            set
            {
                OnRouteNameChanging(value);
                ReportPropertyChanging("RouteName");
                _RouteName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RouteName");
                OnRouteNameChanged();
            }
        }
        private global::System.String _RouteName;
        partial void OnRouteNameChanging(global::System.String value);
        partial void OnRouteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RouteUrl
        {
            get
            {
                return _RouteUrl;
            }
            set
            {
                OnRouteUrlChanging(value);
                ReportPropertyChanging("RouteUrl");
                _RouteUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RouteUrl");
                OnRouteUrlChanged();
            }
        }
        private global::System.String _RouteUrl;
        partial void OnRouteUrlChanging(global::System.String value);
        partial void OnRouteUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhysicalFile
        {
            get
            {
                return _PhysicalFile;
            }
            set
            {
                OnPhysicalFileChanging(value);
                ReportPropertyChanging("PhysicalFile");
                _PhysicalFile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhysicalFile");
                OnPhysicalFileChanged();
            }
        }
        private global::System.String _PhysicalFile;
        partial void OnPhysicalFileChanging(global::System.String value);
        partial void OnPhysicalFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CheckPhysicalUrlAccess
        {
            get
            {
                return _CheckPhysicalUrlAccess;
            }
            set
            {
                OnCheckPhysicalUrlAccessChanging(value);
                ReportPropertyChanging("CheckPhysicalUrlAccess");
                _CheckPhysicalUrlAccess = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CheckPhysicalUrlAccess");
                OnCheckPhysicalUrlAccessChanged();
            }
        }
        private global::System.Boolean _CheckPhysicalUrlAccess;
        partial void OnCheckPhysicalUrlAccessChanging(global::System.Boolean value);
        partial void OnCheckPhysicalUrlAccessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RouteValueDictionary
        {
            get
            {
                return _RouteValueDictionary;
            }
            set
            {
                OnRouteValueDictionaryChanging(value);
                ReportPropertyChanging("RouteValueDictionary");
                _RouteValueDictionary = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RouteValueDictionary");
                OnRouteValueDictionaryChanged();
            }
        }
        private global::System.String _RouteValueDictionary;
        partial void OnRouteValueDictionaryChanging(global::System.String value);
        partial void OnRouteValueDictionaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ListOrder
        {
            get
            {
                return _ListOrder;
            }
            set
            {
                OnListOrderChanging(value);
                ReportPropertyChanging("ListOrder");
                _ListOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListOrder");
                OnListOrderChanged();
            }
        }
        private global::System.Int32 _ListOrder;
        partial void OnListOrderChanging(global::System.Int32 value);
        partial void OnListOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Discontinued
        {
            get
            {
                return _Discontinued;
            }
            set
            {
                OnDiscontinuedChanging(value);
                ReportPropertyChanging("Discontinued");
                _Discontinued = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discontinued");
                OnDiscontinuedChanged();
            }
        }
        private global::System.Boolean _Discontinued;
        partial void OnDiscontinuedChanging(global::System.Boolean value);
        partial void OnDiscontinuedChanged();

        #endregion
    
    }

    #endregion
    
}
