<?xml version="1.0" encoding="utf-8"?><Database Name="5eagle_VBA" Class="TabDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=23.91.114.136;Initial Catalog=5eagle_VBA;User ID=VBA_USER" SettingsObjectName="CommonLibrary.Properties.Settings" SettingsPropertyName="_5eagle_VBAConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Tabs" Member="aspnet_Tabs">
    <Type Name="aspnet_Tab">
      <Column Name="TabId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContentItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PortalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TabOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TabName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lineage" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DisableLink" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DisplayTitle" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TabPath" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RouteId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PageHeadText" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PageFooterText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PageControlBar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSecure" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PermanentRedirect" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SiteMapPriority" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CssClass" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IconFile" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IconFileLarge" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CultureCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastModifiedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>