#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="5eagle_VBA")]
	public partial class GalleryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGallery_File(Gallery_File instance);
    partial void UpdateGallery_File(Gallery_File instance);
    partial void DeleteGallery_File(Gallery_File instance);
    partial void InsertGallery_Topic(Gallery_Topic instance);
    partial void UpdateGallery_Topic(Gallery_Topic instance);
    partial void DeleteGallery_Topic(Gallery_Topic instance);
    partial void InsertGallery_Collection_File(Gallery_Collection_File instance);
    partial void UpdateGallery_Collection_File(Gallery_Collection_File instance);
    partial void DeleteGallery_Collection_File(Gallery_Collection_File instance);
    partial void InsertGallery_Collection(Gallery_Collection instance);
    partial void UpdateGallery_Collection(Gallery_Collection instance);
    partial void DeleteGallery_Collection(Gallery_Collection instance);
    #endregion
		
		public GalleryDataContext() : 
				base(global::GalleryLibrary.Properties.Settings.Default._5eagle_VBAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GalleryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GalleryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GalleryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GalleryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Gallery_File> Gallery_Files
		{
			get
			{
				return this.GetTable<Gallery_File>();
			}
		}
		
		public System.Data.Linq.Table<Gallery_Topic> Gallery_Topics
		{
			get
			{
				return this.GetTable<Gallery_Topic>();
			}
		}
		
		public System.Data.Linq.Table<Gallery_Collection_File> Gallery_Collection_Files
		{
			get
			{
				return this.GetTable<Gallery_Collection_File>();
			}
		}
		
		public System.Data.Linq.Table<Gallery_Collection> Gallery_Collections
		{
			get
			{
				return this.GetTable<Gallery_Collection>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Gallery.Gallery_Topics_Insert")]
		public int Gallery_Topics_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string ip, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string alias, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parentid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_return)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, ip, name, alias, parentid, description, status, o_return);
			o_return = ((System.Nullable<int>)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Gallery.Gallery_Topics_Update")]
		public int Gallery_Topics_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string ip, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idx, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string alias, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parentid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_return)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, ip, idx, name, alias, parentid, description, status, o_return);
			o_return = ((System.Nullable<int>)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Gallery.Gallery_Files")]
	public partial class Gallery_File : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FileId;
		
		private string _FileName;
		
		private string _FileUrl;
		
		private string _Description;
		
		private System.Nullable<int> _ListOrder;
		
		private string _Tags;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<System.DateTime> _LastModifieddDate;
		
		private System.Nullable<System.Guid> _UserLog;
		
		private System.Nullable<System.Guid> _UserLastUpdate;
		
		private string _IPLog;
		
		private string _IPLastUpdate;
		
		private char _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileIdChanging(int value);
    partial void OnFileIdChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnFileUrlChanging(string value);
    partial void OnFileUrlChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnListOrderChanging(System.Nullable<int> value);
    partial void OnListOrderChanged();
    partial void OnTagsChanging(string value);
    partial void OnTagsChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifieddDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifieddDateChanged();
    partial void OnUserLogChanging(System.Nullable<System.Guid> value);
    partial void OnUserLogChanged();
    partial void OnUserLastUpdateChanging(System.Nullable<System.Guid> value);
    partial void OnUserLastUpdateChanged();
    partial void OnIPLogChanging(string value);
    partial void OnIPLogChanged();
    partial void OnIPLastUpdateChanging(string value);
    partial void OnIPLastUpdateChanged();
    partial void OnStatusChanging(char value);
    partial void OnStatusChanged();
    #endregion
		
		public Gallery_File()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FileId
		{
			get
			{
				return this._FileId;
			}
			set
			{
				if ((this._FileId != value))
				{
					this.OnFileIdChanging(value);
					this.SendPropertyChanging();
					this._FileId = value;
					this.SendPropertyChanged("FileId");
					this.OnFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(500)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileUrl", DbType="NVarChar(500)")]
		public string FileUrl
		{
			get
			{
				return this._FileUrl;
			}
			set
			{
				if ((this._FileUrl != value))
				{
					this.OnFileUrlChanging(value);
					this.SendPropertyChanging();
					this._FileUrl = value;
					this.SendPropertyChanged("FileUrl");
					this.OnFileUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListOrder", DbType="Int")]
		public System.Nullable<int> ListOrder
		{
			get
			{
				return this._ListOrder;
			}
			set
			{
				if ((this._ListOrder != value))
				{
					this.OnListOrderChanging(value);
					this.SendPropertyChanging();
					this._ListOrder = value;
					this.SendPropertyChanged("ListOrder");
					this.OnListOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="NVarChar(250)")]
		public string Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				if ((this._Tags != value))
				{
					this.OnTagsChanging(value);
					this.SendPropertyChanging();
					this._Tags = value;
					this.SendPropertyChanged("Tags");
					this.OnTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifieddDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifieddDate
		{
			get
			{
				return this._LastModifieddDate;
			}
			set
			{
				if ((this._LastModifieddDate != value))
				{
					this.OnLastModifieddDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifieddDate = value;
					this.SendPropertyChanged("LastModifieddDate");
					this.OnLastModifieddDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLog", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserLog
		{
			get
			{
				return this._UserLog;
			}
			set
			{
				if ((this._UserLog != value))
				{
					this.OnUserLogChanging(value);
					this.SendPropertyChanging();
					this._UserLog = value;
					this.SendPropertyChanged("UserLog");
					this.OnUserLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLastUpdate", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserLastUpdate
		{
			get
			{
				return this._UserLastUpdate;
			}
			set
			{
				if ((this._UserLastUpdate != value))
				{
					this.OnUserLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._UserLastUpdate = value;
					this.SendPropertyChanged("UserLastUpdate");
					this.OnUserLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPLog", DbType="VarChar(30)")]
		public string IPLog
		{
			get
			{
				return this._IPLog;
			}
			set
			{
				if ((this._IPLog != value))
				{
					this.OnIPLogChanging(value);
					this.SendPropertyChanging();
					this._IPLog = value;
					this.SendPropertyChanged("IPLog");
					this.OnIPLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPLastUpdate", DbType="VarChar(30)")]
		public string IPLastUpdate
		{
			get
			{
				return this._IPLastUpdate;
			}
			set
			{
				if ((this._IPLastUpdate != value))
				{
					this.OnIPLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._IPLastUpdate = value;
					this.SendPropertyChanged("IPLastUpdate");
					this.OnIPLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1) NOT NULL")]
		public char Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Gallery.Gallery_Topics")]
	public partial class Gallery_Topic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Gallery_TopicId;
		
		private string _Gallery_TopicName;
		
		private string _Alias;
		
		private int _ParentId;
		
		private string _Depth;
		
		private string _Lineage;
		
		private System.Nullable<int> _SortKey;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _PostedDate;
		
		private System.Nullable<System.DateTime> _LastUpdatedDate;
		
		private System.Nullable<System.Guid> _UserLog;
		
		private System.Nullable<System.Guid> _UserLastUpdate;
		
		private string _IPLog;
		
		private string _IPLastUpdate;
		
		private char _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGallery_TopicIdChanging(int value);
    partial void OnGallery_TopicIdChanged();
    partial void OnGallery_TopicNameChanging(string value);
    partial void OnGallery_TopicNameChanged();
    partial void OnAliasChanging(string value);
    partial void OnAliasChanged();
    partial void OnParentIdChanging(int value);
    partial void OnParentIdChanged();
    partial void OnDepthChanging(string value);
    partial void OnDepthChanged();
    partial void OnLineageChanging(string value);
    partial void OnLineageChanged();
    partial void OnSortKeyChanging(System.Nullable<int> value);
    partial void OnSortKeyChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPostedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPostedDateChanged();
    partial void OnLastUpdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdatedDateChanged();
    partial void OnUserLogChanging(System.Nullable<System.Guid> value);
    partial void OnUserLogChanged();
    partial void OnUserLastUpdateChanging(System.Nullable<System.Guid> value);
    partial void OnUserLastUpdateChanged();
    partial void OnIPLogChanging(string value);
    partial void OnIPLogChanged();
    partial void OnIPLastUpdateChanging(string value);
    partial void OnIPLastUpdateChanged();
    partial void OnStatusChanging(char value);
    partial void OnStatusChanged();
    #endregion
		
		public Gallery_Topic()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gallery_TopicId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Gallery_TopicId
		{
			get
			{
				return this._Gallery_TopicId;
			}
			set
			{
				if ((this._Gallery_TopicId != value))
				{
					this.OnGallery_TopicIdChanging(value);
					this.SendPropertyChanging();
					this._Gallery_TopicId = value;
					this.SendPropertyChanged("Gallery_TopicId");
					this.OnGallery_TopicIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gallery_TopicName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Gallery_TopicName
		{
			get
			{
				return this._Gallery_TopicName;
			}
			set
			{
				if ((this._Gallery_TopicName != value))
				{
					this.OnGallery_TopicNameChanging(value);
					this.SendPropertyChanging();
					this._Gallery_TopicName = value;
					this.SendPropertyChanged("Gallery_TopicName");
					this.OnGallery_TopicNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this.OnAliasChanging(value);
					this.SendPropertyChanging();
					this._Alias = value;
					this.SendPropertyChanged("Alias");
					this.OnAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int NOT NULL")]
		public int ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Depth", DbType="VarChar(20)")]
		public string Depth
		{
			get
			{
				return this._Depth;
			}
			set
			{
				if ((this._Depth != value))
				{
					this.OnDepthChanging(value);
					this.SendPropertyChanging();
					this._Depth = value;
					this.SendPropertyChanged("Depth");
					this.OnDepthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lineage", DbType="VarChar(250)")]
		public string Lineage
		{
			get
			{
				return this._Lineage;
			}
			set
			{
				if ((this._Lineage != value))
				{
					this.OnLineageChanging(value);
					this.SendPropertyChanging();
					this._Lineage = value;
					this.SendPropertyChanged("Lineage");
					this.OnLineageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortKey", DbType="Int")]
		public System.Nullable<int> SortKey
		{
			get
			{
				return this._SortKey;
			}
			set
			{
				if ((this._SortKey != value))
				{
					this.OnSortKeyChanging(value);
					this.SendPropertyChanging();
					this._SortKey = value;
					this.SendPropertyChanged("SortKey");
					this.OnSortKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PostedDate
		{
			get
			{
				return this._PostedDate;
			}
			set
			{
				if ((this._PostedDate != value))
				{
					this.OnPostedDateChanging(value);
					this.SendPropertyChanging();
					this._PostedDate = value;
					this.SendPropertyChanged("PostedDate");
					this.OnPostedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdatedDate
		{
			get
			{
				return this._LastUpdatedDate;
			}
			set
			{
				if ((this._LastUpdatedDate != value))
				{
					this.OnLastUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdatedDate = value;
					this.SendPropertyChanged("LastUpdatedDate");
					this.OnLastUpdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLog", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserLog
		{
			get
			{
				return this._UserLog;
			}
			set
			{
				if ((this._UserLog != value))
				{
					this.OnUserLogChanging(value);
					this.SendPropertyChanging();
					this._UserLog = value;
					this.SendPropertyChanged("UserLog");
					this.OnUserLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLastUpdate", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserLastUpdate
		{
			get
			{
				return this._UserLastUpdate;
			}
			set
			{
				if ((this._UserLastUpdate != value))
				{
					this.OnUserLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._UserLastUpdate = value;
					this.SendPropertyChanged("UserLastUpdate");
					this.OnUserLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPLog", DbType="VarChar(30)")]
		public string IPLog
		{
			get
			{
				return this._IPLog;
			}
			set
			{
				if ((this._IPLog != value))
				{
					this.OnIPLogChanging(value);
					this.SendPropertyChanging();
					this._IPLog = value;
					this.SendPropertyChanged("IPLog");
					this.OnIPLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPLastUpdate", DbType="VarChar(30)")]
		public string IPLastUpdate
		{
			get
			{
				return this._IPLastUpdate;
			}
			set
			{
				if ((this._IPLastUpdate != value))
				{
					this.OnIPLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._IPLastUpdate = value;
					this.SendPropertyChanged("IPLastUpdate");
					this.OnIPLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1) NOT NULL")]
		public char Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Gallery.Gallery_Collection_Files")]
	public partial class Gallery_Collection_File : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CollectionFileId;
		
		private int _CollectionId;
		
		private int _FileId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCollectionFileIdChanging(int value);
    partial void OnCollectionFileIdChanged();
    partial void OnCollectionIdChanging(int value);
    partial void OnCollectionIdChanged();
    partial void OnFileIdChanging(int value);
    partial void OnFileIdChanged();
    #endregion
		
		public Gallery_Collection_File()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectionFileId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CollectionFileId
		{
			get
			{
				return this._CollectionFileId;
			}
			set
			{
				if ((this._CollectionFileId != value))
				{
					this.OnCollectionFileIdChanging(value);
					this.SendPropertyChanging();
					this._CollectionFileId = value;
					this.SendPropertyChanged("CollectionFileId");
					this.OnCollectionFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectionId", DbType="Int NOT NULL")]
		public int CollectionId
		{
			get
			{
				return this._CollectionId;
			}
			set
			{
				if ((this._CollectionId != value))
				{
					this.OnCollectionIdChanging(value);
					this.SendPropertyChanging();
					this._CollectionId = value;
					this.SendPropertyChanged("CollectionId");
					this.OnCollectionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileId", DbType="Int NOT NULL")]
		public int FileId
		{
			get
			{
				return this._FileId;
			}
			set
			{
				if ((this._FileId != value))
				{
					this.OnFileIdChanging(value);
					this.SendPropertyChanging();
					this._FileId = value;
					this.SendPropertyChanged("FileId");
					this.OnFileIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Gallery.Gallery_Collections")]
	public partial class Gallery_Collection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TopicId;
		
		private int _CollectionId;
		
		private string _Title;
		
		private string _IconFile;
		
		private System.Nullable<int> _ListOrder;
		
		private string _Description;
		
		private string _Tags;
		
		private string _Url;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<System.DateTime> _LastModifieddDate;
		
		private System.Nullable<System.Guid> _UserLog;
		
		private System.Nullable<System.Guid> _UserLastUpdate;
		
		private string _IPLog;
		
		private string _IPLastUpdate;
		
		private char _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTopicIdChanging(int value);
    partial void OnTopicIdChanged();
    partial void OnCollectionIdChanging(int value);
    partial void OnCollectionIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnIconFileChanging(string value);
    partial void OnIconFileChanged();
    partial void OnListOrderChanging(System.Nullable<int> value);
    partial void OnListOrderChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnTagsChanging(string value);
    partial void OnTagsChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifieddDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifieddDateChanged();
    partial void OnUserLogChanging(System.Nullable<System.Guid> value);
    partial void OnUserLogChanged();
    partial void OnUserLastUpdateChanging(System.Nullable<System.Guid> value);
    partial void OnUserLastUpdateChanged();
    partial void OnIPLogChanging(string value);
    partial void OnIPLogChanged();
    partial void OnIPLastUpdateChanging(string value);
    partial void OnIPLastUpdateChanged();
    partial void OnStatusChanging(char value);
    partial void OnStatusChanged();
    #endregion
		
		public Gallery_Collection()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopicId", DbType="Int NOT NULL")]
		public int TopicId
		{
			get
			{
				return this._TopicId;
			}
			set
			{
				if ((this._TopicId != value))
				{
					this.OnTopicIdChanging(value);
					this.SendPropertyChanging();
					this._TopicId = value;
					this.SendPropertyChanged("TopicId");
					this.OnTopicIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CollectionId
		{
			get
			{
				return this._CollectionId;
			}
			set
			{
				if ((this._CollectionId != value))
				{
					this.OnCollectionIdChanging(value);
					this.SendPropertyChanging();
					this._CollectionId = value;
					this.SendPropertyChanged("CollectionId");
					this.OnCollectionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(350) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconFile", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string IconFile
		{
			get
			{
				return this._IconFile;
			}
			set
			{
				if ((this._IconFile != value))
				{
					this.OnIconFileChanging(value);
					this.SendPropertyChanging();
					this._IconFile = value;
					this.SendPropertyChanged("IconFile");
					this.OnIconFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListOrder", DbType="Int")]
		public System.Nullable<int> ListOrder
		{
			get
			{
				return this._ListOrder;
			}
			set
			{
				if ((this._ListOrder != value))
				{
					this.OnListOrderChanging(value);
					this.SendPropertyChanging();
					this._ListOrder = value;
					this.SendPropertyChanged("ListOrder");
					this.OnListOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="NVarChar(4000)")]
		public string Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				if ((this._Tags != value))
				{
					this.OnTagsChanging(value);
					this.SendPropertyChanging();
					this._Tags = value;
					this.SendPropertyChanged("Tags");
					this.OnTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(500)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifieddDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifieddDate
		{
			get
			{
				return this._LastModifieddDate;
			}
			set
			{
				if ((this._LastModifieddDate != value))
				{
					this.OnLastModifieddDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifieddDate = value;
					this.SendPropertyChanged("LastModifieddDate");
					this.OnLastModifieddDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLog", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserLog
		{
			get
			{
				return this._UserLog;
			}
			set
			{
				if ((this._UserLog != value))
				{
					this.OnUserLogChanging(value);
					this.SendPropertyChanging();
					this._UserLog = value;
					this.SendPropertyChanged("UserLog");
					this.OnUserLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLastUpdate", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserLastUpdate
		{
			get
			{
				return this._UserLastUpdate;
			}
			set
			{
				if ((this._UserLastUpdate != value))
				{
					this.OnUserLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._UserLastUpdate = value;
					this.SendPropertyChanged("UserLastUpdate");
					this.OnUserLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPLog", DbType="VarChar(30)")]
		public string IPLog
		{
			get
			{
				return this._IPLog;
			}
			set
			{
				if ((this._IPLog != value))
				{
					this.OnIPLogChanging(value);
					this.SendPropertyChanging();
					this._IPLog = value;
					this.SendPropertyChanged("IPLog");
					this.OnIPLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPLastUpdate", DbType="VarChar(30)")]
		public string IPLastUpdate
		{
			get
			{
				return this._IPLastUpdate;
			}
			set
			{
				if ((this._IPLastUpdate != value))
				{
					this.OnIPLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._IPLastUpdate = value;
					this.SendPropertyChanged("IPLastUpdate");
					this.OnIPLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1) NOT NULL")]
		public char Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
